package UI;

import javax.swing.*;
import java.awt.CardLayout;

/**
 * Primary application window for the Story Keeper App.
 * <p>
 * Manages a card-based layout to switch between login, registration,
 * and the main home UI.
 * </p>
 * 
 * Usage:
 * <pre>
 *     Frame frame = new Frame();
 *     frame.setVisible(true);
 * </pre>
 * 
 * @author evandex
 */
public class Frame extends JFrame {

    /**
     * The login screen panel.
     */
    private Login loginCard;
    
    /**
     * The registration screen panel.
     */
    private Register registerCard;
    
    /**
     * The home layout panel, shown after successful login.
     */
    private HomeLayout homeLayoutCard;
    
    /**
     * The CardLayout controlling {@link #mainPanel} content.
     */
    private CardLayout outerCard;
    
    /**
     * Constructs the main application frame, initializing
     * components and setting up the login and register cards.
     * <p>
     * Center the window on screen and default to showing the login card.
     * </p>
     */
    public Frame() {
        initComponents();
        setLocationRelativeTo(null);
        loginCard = new Login(this);
        registerCard = new Register();
        
        mainPanel.add(loginCard, "login");
        mainPanel.add(registerCard, "register");
        mainPanel.add(new JPanel(), "homelayout");
        outerCard = (CardLayout) mainPanel.getLayout();
        outerCard.show(mainPanel, "login");
    }
    
    /**
     * Switches the view to the main home UI after a successful login.
     * <p>
     * Instantiates and adds the {@link HomeLayout} panel, then
     * displays it and triggers its {@code onShow()} lifecycle method.
     * </p>
     */
    public void showMainUI() {
        homeLayoutCard = new HomeLayout(loginCard);
        mainPanel.add(homeLayoutCard, "homelayout");
        outerCard.show(mainPanel, "homelayout");
        homeLayoutCard.onShow();
    }
    /**
     * Called by the constructor to initialize and configure Swing components.
     * <p>
     * WARNING: Do NOT modify this code. It is regenerated by the Form Editor.
     * </p>
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Story Keeper App");
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
