/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import DAO.TraitDAO;
import java.sql.SQLException;
import javax.swing.*;

/**
 * Dialog window for renaming an existing trait.
 * <p>
 * Displays text fields for the old and new trait names, and buttons to
 * confirm or cancel the rename operation. Delegates the rename logic to
 * {@link TraitDAO}.
 * </p>
 * 
 * @see TraitDAO
 * 
 * @author evandex
 */
public class TraitEditDialog extends javax.swing.JDialog {

    /**
     * Constructs the rename-trait dialog.
     *
     * @param parent the parent frame over which this dialog is centered
     * @param modal  whether the dialog blocks input to other windows when shown
     */
    public TraitEditDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(parent);
        setSize(200, 150);
    }

    /**
     * Initializes Swing components.
     * <p>
     * WARNING: This code is auto-generated by the Form Editor and will be
     * regenerated if the form is modified. Do NOT manually edit this block.
     * </p>
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        newTraitField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        renameButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        oldTraitField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rename Trait");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel2.setText("Rename to:");
        jPanel2.add(jLabel2);

        newTraitField.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(newTraitField);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 10));

        renameButton.setText("Rename");
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });
        jPanel3.add(renameButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel3.setText("Trait name:");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel4.add(jLabel3);

        oldTraitField.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel4.add(oldTraitField);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the "Cancel" button click by closing the dialog without changes.
     *
     * @param evt the action event (ignored)
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Handles the "Rename" button click.
     * <p>
     * Reads the old and new trait names from the respective text fields,
     * calls {@link TraitDAO#renameTrait(String,String)}, and shows a
     * success or error message. Closes the dialog on successful rename.
     * Always closes the DAO connection in a finally block.
     * </p>
     *
     * @param evt the action event (ignored)
     */
    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        String oldTrait = oldTraitField.getText();
        String newTrait = newTraitField.getText();
        TraitDAO traitRename = new TraitDAO();
        try {
            if (traitRename.renameTrait(oldTrait, newTrait)) {
                JOptionPane.showMessageDialog(this, "Successfully renamed trait.", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Trait renaming failed.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            traitRename.closeConnection();
        }
    }//GEN-LAST:event_renameButtonActionPerformed

    /**
     * Application entry point for standalone testing of the dialog.
     * <p>
     * Sets the Nimbus look and feel (if available), then creates and
     * displays the dialog. Exits the JVM when the dialog window is closed.
     * </p>
     *
     * @param args command-line arguments (ignored)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraitEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraitEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraitEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraitEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TraitEditDialog dialog = new TraitEditDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField newTraitField;
    private javax.swing.JTextField oldTraitField;
    private javax.swing.JButton renameButton;
    // End of variables declaration//GEN-END:variables
}
