/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import DAO.TraitDAO;
import javax.swing.SwingWorker;
import javax.swing.JOptionPane;

/**
 * The design is temporary. Change it later!
 */
public class TraitDialog extends javax.swing.JDialog {
    private boolean disableConfirmation = false;
    /**
     * Creates new form TraitDialog
     */
    public TraitDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(parent);
        setSize(200, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        traitField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        confirmCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Character Trait");
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setText("   Trait:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout(5, 5));
        jPanel1.add(traitField, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton);

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel2.add(doneButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        confirmCheck.setText("Disable confirmation pop-up");
        confirmCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmCheckActionPerformed(evt);
            }
        });
        jPanel1.add(confirmCheck, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addButton.setEnabled(false);
        doneButton.setEnabled(false);
        new SwingWorker<Boolean, Void>() {
            private String trait = traitField.getText();
            private String errorMsg = null;

            @Override
            protected Boolean doInBackground() {
                TraitDAO traitAdder = new TraitDAO();
                try {
                    if (traitAdder.checkTrait(trait)) {
                        errorMsg = "Trait already exists. Please enter a different trait.";
                        return false;
                        }
                    boolean created = traitAdder.addTrait(trait);
                    if (!created) errorMsg = "Failed to add trait.";
                    return created;
                } catch (Exception ex) {
                    errorMsg = "Database error: " + ex.getMessage();
                    ex.printStackTrace();
                    return false;
                } finally {
                    traitAdder.closeConnection();
                }
            }
            @Override
            protected void done() {
                addButton.setEnabled(true);
                doneButton.setEnabled(true);
                
                boolean success = false;
                try {
                    success = get();
                } catch (Exception ex) {
                    errorMsg = "Unexpected error: " + ex.getMessage();
                }

                if (success && !disableConfirmation) {
                    JOptionPane.showMessageDialog(
                        TraitDialog.this,
                        "Trait successfully added!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                } else if (!success) {
                    JOptionPane.showMessageDialog(
                        TraitDialog.this,
                        errorMsg,
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        }.execute();
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void confirmCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmCheckActionPerformed
        if (confirmCheck.isSelected())
            disableConfirmation = true;
        
    }//GEN-LAST:event_confirmCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TraitDialog dialog = new TraitDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JCheckBox confirmCheck;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField traitField;
    // End of variables declaration//GEN-END:variables
}
